create table person
(
id integer not null,
name varchar(255) not null,
location varchar(255),
birthdate timestamp,
primary key (id)
);

INSERT INTO person (ID,NAME,LOCATION,BIRTHDATE) VALUES(10001,'Levo','Bursa',sysdate());
INSERT INTO person (ID,NAME,LOCATION,BIRTHDATE) VALUES(10002,'Tezo','Ankara',sysdate());
INSERT INTO person (ID,NAME,LOCATION,BIRTHDATE) VALUES(10003,'Kazo','Uskudar',sysdate());
INSERT INTO person (ID,NAME,LOCATION,BIRTHDATE) VALUES(10004,'Erko','Uskudar',sysdate());



INSERT INTO "OFFERBUY"("ID","CC","CC_TYPE","CREDATE","DESC","MONEY","MONEY_TYPE","SUM","USER")VALUES(1,1,'BTC',sysdate(),'ACIKLAMAMDIR',1,'TRY',1,'LEVO');
INSERT INTO "OFFERBUY"("ID","CC","CC_TYPE","CREDATE","DESC","MONEY","MONEY_TYPE","SUM","USER")VALUES(2,1,'BTC',sysdate(),'ACIKLAMA2',1,'TRY',2,'LEVO');
INSERT INTO "OFFERBUY"("ID","CC","CC_TYPE","CREDATE","DESC","MONEY","MONEY_TYPE","SUM","USER")VALUES(3,1,'BTC',sysdate(),'ACIKLAMA3',1,'TRY',3,'LEVO');
INSERT INTO "OFFERBUY"("ID","CC","CC_TYPE","CREDATE","DESC","MONEY","MONEY_TYPE","SUM","USER")VALUES(4,1,'BTC',sysdate(),'ACIKLAMA4',1,'TRY',4,'LEVO');
INSERT INTO "OFFERBUY"("ID","CC","CC_TYPE","CREDATE","DESC","MONEY","MONEY_TYPE","SUM","USER")VALUES(5,1,'BTC',sysdate(),'ACIKLAMA5',1,'TRY',5,'LEVO');


INSERT INTO "OFFERSELL"("ID","CC","CC_TYPE","CREDATE","DESC","MONEY","MONEY_TYPE","SUM","USER")VALUES(1,1,'BTC',sysdate(),'ACIKLAMAMDIR',1,'TRY',1,'LEVO');
INSERT INTO "OFFERSELL"("ID","CC","CC_TYPE","CREDATE","DESC","MONEY","MONEY_TYPE","SUM","USER")VALUES(2,1,'BTC',sysdate(),'ACIKLAMA2',1,'TRY',2,'LEVO');
INSERT INTO "OFFERSELL"("ID","CC","CC_TYPE","CREDATE","DESC","MONEY","MONEY_TYPE","SUM","USER")VALUES(3,1,'BTC',sysdate(),'ACIKLAMA3',1,'TRY',3,'LEVO');
INSERT INTO "OFFERSELL"("ID","CC","CC_TYPE","CREDATE","DESC","MONEY","MONEY_TYPE","SUM","USER")VALUES(4,1,'BTC',sysdate(),'ACIKLAMA4',1,'TRY',4,'LEVO');
INSERT INTO "OFFERSELL"("ID","CC","CC_TYPE","CREDATE","DESC","MONEY","MONEY_TYPE","SUM","USER")VALUES(5,1,'BTC',sysdate(),'ACIKLAMA5',1,'TRY',5,'LEVO');